### ISSUE TITLE
go panic when converting hygieia docker-compose

### ISSUE THREAD

**Issue by raffaelespazzoli** [kubernetes-incubator/kompose#173]
the file can be found here:
https://raw.githubusercontent.com/capitalone/Hygieia/master/docker-compose.yml

**Comment by sebgoa** [comment]
@raffaelespazzoli can you copy the error you are getting in this issue.
thanks

**Comment by ngtuna** [comment]
@raffaelespazzoli : The panic comes from libcompose parsing function. 
```console
$ kompose --file hygieia.yml convert 
WARN[0000] Unsupported key volume_driver - ignoring     
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x15b1de0, 0xc82000e170)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/yaml.toMap(0xc8203a6720, 0x3, 0x3, 0x1814c78, 0x1, 0x40)
	/home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/yaml/types_yaml.go:223 +0x187
github.com/skippbox/kompose/vendor/github.com/docker/libcompose/yaml.(*MaporEqualSlice).ToMap(0xc8201b92d0, 0xc8201b9180)
	/home/tuna/workspace/gocode-kompose/src/github.com/skippbox/kompose/vendor/github.com/docker/libcompose/yaml/types_yaml.go:126 +0x4b
github.com/skippbox/kompose/pkg/loader/compose.(*Compose).LoadFile(0x24e87f0, 0xc8204cb150, 0xb, 0x0)

```

@sebgoa It's another sample motivating us to upgrade libcompose. Like this one: #149

**Comment by ngtuna** [comment]
@raffaelespazzoli you got it passed on master branch now.
