### ISSUE TITLE
Panics parsing volume config

### ISSUE THREAD

**Issue by spullara** [kubernetes-incubator/kompose#471]
I think it maybe because they are at the top level

```
version: '2'
volumes:
  dynamo_db:
  redis:
```

then defined later in particular services:

```
    volumes:
     - dynamo_db:/var/dynamodb_local
```

exception:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x90b6d7]

goroutine 1 [running]:
panic(0x15e3920, 0xc420010070)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).handleVolumeConfig(0xc4200440e0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:319 +0x1d7
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).load(0xc4200440e0, 0x7fff5fbff8f3, 0x17, 0xc420218d80, 0x249, 0x449, 0xc4204c1408, 0xfe88)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:235 +0x3a0
github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project.(*Project).Parse(0xc4200440e0, 0x0, 0x0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/docker/libcompose/project/project.go:112 +0x15a
github.com/kubernetes-incubator/kompose/pkg/loader/compose.(*Compose).LoadFile(0x25e0eb8, 0xc4201f4ee0, 0x1, 0x1, 0xc420040990, 0x0, 0xf65e)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/pkg/loader/compose/compose.go:262 +0x1c1
github.com/kubernetes-incubator/kompose/pkg/app.Convert(0x100000100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc4201f4ee0, 0x1, 0x1, ...)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/pkg/app/app.go:195 +0x103
github.com/kubernetes-incubator/kompose/cmd.glob..func3(0x25b3120, 0xc42000fba0, 0x0, 0x2)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/cmd/convert.go:80 +0x3f
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).execute(0x25b3120, 0xc42000f900, 0x2, 0x2, 0x25b3120, 0xc42000f900)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25b3560, 0xc42006c058, 0x0, 0xc4204c1ed0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra.(*Command).Execute(0x25b3560, 0x0, 0x0)
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/kubernetes-incubator/kompose/cmd.Execute()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/cmd/root.go:92 +0x31
main.main()
	/home/wikus/dropbox/dev/go/src/github.com/kubernetes-incubator/kompose/main.go:22 +0x14
```

**Comment by kadel** [comment]
Hi @spullara,
Thank you for reporting it. It looks like this is issue in libcompose - https://github.com/docker/libcompose/issues/430 . Should be fixed in next release.

**Comment by cdrage** [comment]
@kadel Perhaps we can update the vendoring for Kompose ? :+1:

**Comment by kadel** [comment]
yep, lets update vendored libcopmose  and test  it. So we can get this to next release
